### PR TITLE
fix: team invite to work with new login flow

### LINKED ISSUE #269: Update team invite to work with new login/signup flow
* We used to have passwordless (magic link login), this PR #260 removes that flow and we are going with email/password flow.
* Team invite flow may be broken because we implemented it using magic login verificationToken.
* PR #260 has implemented password reset token flow, we could use that instead to invite the user and let invited team member setup a password.

Both of these flows are broken right now
* Invite a team member
* Invite multiple team member

CleanShot 2024-04-26 at 02 19 59

CleanShot 2024-04-26 at 02 17 09

### PR DESCRIPTION
**Pull request by ksushant6566**
fixes #269

Updated flow 
image

### CODE REVIEW

**Review by dahal — CHANGES_REQUESTED** [review]
Great job on this PR @ksushant6566, however, there are some changes to the flow we handle out background job, which created some merge conflicts. Do you mind fixing those?

**Comment by ksushant6566** [comment]
Cool, I'll make the required changes

**Comment by ksushant6566** [comment]
@dahal, All conflicts are now resolved. There were lint errors, fixed them too.

**Review by dahal — CHANGES_REQUESTED** [review]
Thanks for making those changes, upon review I found following issues:-

CleanShot 2024-05-20 at 02 32 55


1. Its sending a password reset email, please use `MemberInviteEmail` instead. We may need to create `accept-invite` page where we can allow invited users to set their password. Password reset behavior will work here, but just need a new page with some custom copy around accepting the invitation.

2. As you can see on the screenshot, I am getting `undefined` instead of token

**Comment by ksushant6566** [comment]
I am pretty sure, it was sending the correct email, but let me check and come back

**Comment by ksushant6566** [comment]
This is due to the fact that `SendMemberInviteEmailJob` has the type `email.password-reset`

image

Ideally it should be `email.member-invite` but the `JOB_TYPES` also doesn't have `email.member-invite`

```typescript
export const JOB_TYPES = {
  email: [
    "auth-verify",
    "share-update",
    "share-data-room",
    "password-reset",
    "esign-confirmation",
    "esign-notification",
  ],
  generate: ["esign-pdf"],
} as const;

``` 

Do I just add `email.member-invite` in `JOB_TYPES`  and replace the same in `SendMemberInviteEmailJob` or do I need to something else?

**Comment by dahal** [comment]
> Do I just add email.member-invite in JOB_TYPES and replace the same in SendMemberInviteEmailJob or do I need to something else?

Yes please, lets try that and see if it works.

**Comment by ksushant6566** [comment]
Hey @dahal , I have made the changes. Also attaching a loom.

https://www.loom.com/share/058b412c3ca748489365f549baa23317?sid=882e1482-81f6-4108-a3a9-1b52af4e4a6f

**Review by dahal — APPROVED** [review]
Thanks @ksushant6566 🫡

**Pull request merged**
