### PR TITLE
feat: Create combobox component similar to linear.app

### LINKED ISSUE #380: Implement custom combo-box with keyboard shortcuts
Create a re-usable combobox, similar to that of linear.app and some of our select inputs with it. This repo has a really good example, lets get some inspiration from there

https://github.com/damianricobelli/shadcn-linear-combobox

CleanShot 2024-06-10 at 23 07 13

Some of the places we can apply this combo-box are
* Onboarding form
* Stakeholder modal
* Share class modal
* Create a share modal
* Equity plan modal
* Stock options modal
* Create share multi-step modal
* Safe multi-step modal

### PR DESCRIPTION
**Pull request by VK-RED**
## Things Done in this PR
- Created icons.tsx file
- Created Kbd component
- Created useListenPkey hook, which listens for keypress event and if 'p' key is pressed, it opens popover
- Created Combobox component. 

## Resolves
#380

### Screencast
[Screencast from 2024-06-12 12-54-19.webm](https://github.com/captableinc/captable/assets/130341088/e52f778e-97c0-4a28-9a1b-9f2051f17e15)

### CODE REVIEW

**Comment by VK-RED** [comment]
resolving conflicts ..

**Review by dahal — CHANGES_REQUESTED** [review]
Thanks for submitting this PR @VK-RED this is looking promising. Can you please implement this on those modals

CleanShot 2024-06-12 at 23 37 57

**Comment by VK-RED** [comment]
Sure @dahal I can work on it ..

**Comment by VK-RED** [comment]
Attaching Video of how the component looks .. 

### Screencast
[Screencast from 2024-06-18 12-16-06.webm](https://github.com/captableinc/captable/assets/130341088/14bf1289-6f51-436f-8845-09413b71d227)

**Comment by dahal** [comment]
> Attaching Video of how the component looks ..
> 
> ### Screencast
>  Screencast.from.2024-06-18.12-16-06.webm

Amazing work, thanks for applying this to all dropdown/selectors. Here are few feedbacks after watching the screencast

1. Let's align input values to left
2. When selecting with numerical shortcuts, does it select the value and close right away, i noticed a bit of delay ( i have not tested it locally yet)

**Comment by VK-RED** [comment]
Thanks @dahal for the inputs, will work on the changes.

So, when using the numerical shortcuts, for a single digit  everything is fine, but for the double digits it only chooses the first digit and closes the modal. So deliberately added a delay in useDebounce hook. 

Can I reduce the delay or get rid of the hook as the double digit option occurs only at a single modal ?

**Comment by dahal** [comment]
> Thanks @dahal for the inputs, will work on the changes.
> 
> So, when using the numerical shortcuts, for a single digit everything is fine, but for the double digits it only chooses the first digit and closes the modal. So deliberately added a delay in useDebounce hook.
> 
> Can I reduce the delay or get rid of the hook as the double digit option occurs only at a single modal ?

@VK-RED This component will most likely be used for options less than double digits, so let's get rid of the debounce. We will just have search and select (without shortcut) for options more than 10

**Comment by VK-RED** [comment]
Got it, doing the changes .. 👍

**Comment by VK-RED** [comment]
Applied the changes. 

###Screencast
[Screencast from 2024-06-18 16-16-06.webm](https://github.com/captableinc/captable/assets/130341088/0b56f529-e89b-4b56-b4bd-952b58a25777)

**Review by dahal — APPROVED** [review]
🚀

**Comment by VK-RED** [comment]
🫡

**Pull request merged**
