### PR TITLE
feat: email and password login feature

### LINKED ISSUE #204: Implement email/password login and remove magic link
Passwordless logins are not considered secure. 

* So let's replace it with email/password.
* Implement signup page as well and collect name and email and password
* Send a verification email after a successful signup.
* Send a welcome email using trigger.dev

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes #204 

1. Add credentials provider
2. Verify Email upon new registration
3. Ability to forgot password

### CODE REVIEW

**Comment by anikdhabal** [comment]
I think some update needs

**Review by dahal — CHANGES_REQUESTED** [review]
We have a build error, details on this thread
https://discord.com/channels/1193628549756747776/1203029858385399878/1231472102633377863

**Comment by anikdhabal** [comment]
> We have a build error, details on this thread https://discord.com/channels/1193628549756747776/1203029858385399878/1231472102633377863

Thanks for the review. I will fix that quickly.

**Comment by G3root** [comment]
I believe we need to update the flow for inviting users as we switch to a credential provider. The current invite flow is based on a magic link provider, so passwords might not be included in it.  🤔

**Comment by dahal** [comment]
> I believe we need to update the flow for inviting users as we switch to a credential provider. The current invite flow is based on a magic link provider, so passwords might not be included in it. 🤔

I think we can utilize password reset flow for invitation as well. @anikdhabal lets create a different issue for this.

**Review by dahal — APPROVED** [review]
Amazing work on this PR @anikdhabal . I have created few issues to improve/fix some flows.

#269 & #270

Merging this for now, so above issues are unblocked.

**Comment by anikdhabal** [comment]
Thanks @dahal @G3root for the review. Yes, we need to update the flow. I will fix it.

**Pull request merged**
