### PR TITLE
fix: separated vestingSchedule

### PR DESCRIPTION
**Pull request by Alfredoeb9**
## Issue
Issue: #454 

## Description
separated vestingSchedule into cliffYears and vestingYears

updated prisma tables for Share and Options to separate vestingSchedule into cliffYears and vestingYears with respectable trpc types and updated Shares and Options modal to separate vestingSchedule into two columns cliffYears and vestingYears

### CODE REVIEW

**Review by dahal — CHANGES_REQUESTED** [review]
Thanks for submitting this PR @Alfredoeb9. 

There are some [build errors](https://github.com/captableinc/captable/actions/runs/10027291515/job/27712741728)

CleanShot 2024-07-21 at 04 39 42


You can always make sure the build works by running `pnpm build`

**Review by dahal — CHANGES_REQUESTED** [review]
Looks like we have additional build errors @Alfredoeb9 
https://github.com/captableinc/captable/actions/runs/10035838246/job/27732505821?pr=458

**Comment by Alfredoeb9** [comment]
Fixed build errors mentioned above and tested build and passed with npm build command and with docker compose up --build

**Comment by Alfredoeb9** [comment]
Getting inconsistent webpack build errors nuking branch and setting up again

**Comment by Alfredoeb9** [comment]
After updating docker application, I am no longer seeing random webpack errors and application is running as expected locally. 

Successful build on pnpm build and docker compose up --build

**Review by Alfredoeb9 — COMMENTED** [review]
Review Completed

**Review by dahal — APPROVED** [review]
🚀

**Pull request merged**
